# Generated by Django 3.2 on 2021-08-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_productsreview_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'price']},
        ),
    ]
